// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.BusinessEntity", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Balance");

                    b.Property<string>("City")
                        .HasMaxLength(150);

                    b.Property<string>("Code")
                        .HasMaxLength(50);

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Country")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("CurrentBalance");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email");

                    b.Property<string>("LoginUrl");

                    b.Property<string>("Logo");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50);

                    b.Property<string>("Name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<string>("RefferedBy")
                        .HasMaxLength(50);

                    b.Property<string>("SMTPPassWord");

                    b.Property<int>("SMTPPort");

                    b.Property<string>("SMTPServer");

                    b.Property<string>("SMTPUserName");

                    b.Property<string>("SecurityCode");

                    b.Property<string>("State");

                    b.Property<int>("Status");

                    b.Property<string>("Street");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Zip")
                        .HasMaxLength(50);

                    b.HasKey("BusinessId");

                    b.ToTable("BusinessEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
